Style/FrozenStringLiteralComment:
  Enabled: false


Naming/AccessorMethodName:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/MutableConstant:
  Enabled: false
